# Generated by Django 2.0.3 on 2018-04-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=256)),
                ('price', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
            ],
        ),
    ]
