# Generated by Django 2.0.3 on 2018-04-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proper',
            name='sector',
            field=models.CharField(default=12, max_length=3),
            preserve_default=False,
        ),
    ]
